services:
  ashtachamma:
    image: ashtachamma
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app/app
        - path: ./requirements.txt
          action: rebuild
